// This is an autogenerated file from Firebase Studio.
"use server";
/**
 * @fileOverview A personalized plan generation AI agent.
 *
 * - generatePersonalizedPlan - A function that handles the plan generation process.
 * - GeneratePersonalizedPlanInput - The input type for the generatePersonalizedPlan function.
 * - GeneratePersonalizedPlanOutput - The return type for the generatePersonalizedPlan function.
 */

import { ai } from "@/ai/genkit";
import { z } from "genkit";

const GeneratePersonalizedPlanInputSchema = z.object({
  age: z.coerce.number().describe("The age of the user."),
  height: z.coerce.number().describe("The height of the user in centimeters."),
  weight: z.coerce.number().describe("The weight of the user in kilograms."),
  gender: z
    .enum(["male", "female", "custom"])
    .describe("The gender of the user."),
  activityLevel: z
    .enum([
      "sedentary",
      "lightly_active",
      "moderately_active",
      "very_active",
      "extra_active",
    ])
    .describe("The activity level of the user."),
  fitnessGoals: z
    .string()
    .describe(
      "The fitness goals of the user (e.g., lose weight, build muscle, improve endurance)."
    ),
  dietaryPreferences: z
    .string()
    .describe(
      "The dietary preferences of the user (e.g., vegetarian, vegan, gluten-free)."
    ),
  preferredCuisine: z
    .string()
    .describe(
      "The cuisine preferences of the user (e.g., Italian, Indian, Mexican)."
    ),
  medicalConditions: z
    .string()
    .optional()
    .describe("Any medical conditions the user has."),
  allergies: z.string().optional().describe("Any allergies the user has."),
});
export type GeneratePersonalizedPlanInput = z.infer<
  typeof GeneratePersonalizedPlanInputSchema
>;

const GeneratePersonalizedPlanOutputSchema = z.object({
  dietPlan: z
    .string()
    .describe("A personalized diet plan for the user, formatted in Markdown."),
  workoutPlan: z
    .string()
    .describe(
      "A personalized workout plan for the user, formatted in Markdown."
    ),
  healthTips: z
    .string()
    .describe("Personalized health tips for the user, formatted in Markdown."),
});
export type GeneratePersonalizedPlanOutput = z.infer<
  typeof GeneratePersonalizedPlanOutputSchema
>;

export async function generatePersonalizedPlan(
  input: GeneratePersonalizedPlanInput
): Promise<GeneratePersonalizedPlanOutput> {
  return generatePersonalizedPlanFlow(input);
}

const prompt = ai.definePrompt({
  name: "generatePersonalizedPlanPrompt",
  input: { schema: GeneratePersonalizedPlanInputSchema },
  output: { schema: GeneratePersonalizedPlanOutputSchema },
  system: `You are a personal health and fitness expert. Your task is to generate a personalized diet plan, workout plan, and health tips based on the user's profile. Your response MUST be a single, valid JSON object that strictly adheres to the provided output schema. Do not include any text, explanations, or markdown formatting outside of the JSON structure. Within the JSON fields (dietPlan, workoutPlan, healthTips), use Markdown for formatting (e.g., headings with '##', lists with '*'). Critically, you must consider any medical conditions and allergies listed and tailor the plan to be safe and effective. The diet plan should include specific meal suggestions, the workout plan should include specific exercises and routines, and the health tips should be personalized and actionable.`,
  prompt: `Generate a plan for the following user:
User Profile:
Age: {{{age}}}
Height: {{{height}}} cm
Weight: {{{weight}}} kg
Gender: {{{gender}}}
Activity Level: {{{activityLevel}}}
Fitness Goals: {{{fitnessGoals}}}
Dietary Preferences: {{{dietaryPreferences}}}
Preferred Cuisine: {{{preferredCuisine}}}
{{#if medicalConditions}}
Medical Conditions: {{{medicalConditions}}}
{{/if}}
{{#if allergies}}
Allergies: {{{allergies}}}
{{/if}}`,
  config: {
    safetySettings: [
      {
        category: "HARM_CATEGORY_DANGEROUS_CONTENT",
        threshold: "BLOCK_ONLY_HIGH",
      },
    ],
  },
});

const generatePersonalizedPlanFlow = ai.defineFlow(
  {
    name: "generatePersonalizedPlanFlow",
    inputSchema: GeneratePersonalizedPlanInputSchema,
    outputSchema: GeneratePersonalizedPlanOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    if (!output) {
      throw new Error(
        "The AI model did not return a valid plan. This might be due to a safety policy violation or an empty response."
      );
    }
    return output;
  }
);
