// src/ai/flows/improve-plan-from-feedback.ts
"use server";

/**
 * @fileOverview This file defines a Genkit flow for improving diet and workout plans based on user feedback.
 * It takes user feedback and the original plan as input, and outputs an improved plan.
 *
 * - improvePlanFromFeedback - A function that takes user feedback and the original plan and returns an improved plan.
 * - ImprovePlanFromFeedbackInput - The input type for the improvePlanFromFeedback function.
 * - ImprovePlanFromFeedbackOutput - The return type for the improvePlanFromFeedback function.
 */

import { ai } from "@/ai/genkit";
import { z } from "genkit";

const ImprovePlanFromFeedbackInputSchema = z.object({
  originalPlan: z
    .string()
    .describe("The original diet and workout plan generated by the AI."),
  feedback: z
    .string()
    .describe(
      "User feedback on the original plan, including what they liked and disliked."
    ),
});
export type ImprovePlanFromFeedbackInput = z.infer<
  typeof ImprovePlanFromFeedbackInputSchema
>;

const ImprovePlanFromFeedbackOutputSchema = z
  .string()
  .describe("The improved diet and workout plan based on user feedback.");
export type ImprovePlanFromFeedbackOutput = z.infer<
  typeof ImprovePlanFromFeedbackOutputSchema
>;

export async function improvePlanFromFeedback(
  input: ImprovePlanFromFeedbackInput
): Promise<ImprovePlanFromFeedbackOutput> {
  return improvePlanFromFeedbackFlow(input);
}

const improvePlanFromFeedbackPrompt = ai.definePrompt({
  name: "improvePlanFromFeedbackPrompt",
  input: { schema: ImprovePlanFromFeedbackInputSchema },
  output: { schema: ImprovePlanFromFeedbackOutputSchema },
  prompt: `You are an AI assistant that improves diet and workout plans based on user feedback.

  Original Plan: {{{originalPlan}}}
  Feedback: {{{feedback}}}

  Improve the plan based on the feedback. Ensure the improved plan is detailed and personalized to the user's needs and preferences.
  Provide the complete improved plan as output. Do not include any additional explanation.`,
});

const improvePlanFromFeedbackFlow = ai.defineFlow(
  {
    name: "improvePlanFromFeedbackFlow",
    inputSchema: ImprovePlanFromFeedbackInputSchema,
    outputSchema: ImprovePlanFromFeedbackOutputSchema,
  },
  async (input) => {
    const { output } = await improvePlanFromFeedbackPrompt(input);
    return output!;
  }
);
