export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-lg p-8 md:p-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">⚠️ Disclaimer</h1>
        <p className="text-sm text-gray-500 mb-8">
          Last Updated: October 26, 2025
        </p>

        <div className="prose prose-lg max-w-none">
          <div className="bg-yellow-50 border-l-4 border-yellow-400 p-6 mb-8">
            <p className="text-lg text-gray-800 font-medium mb-4">
              WellNourish AI is an AI-powered diet and nutrition planning tool.
            </p>
          </div>

          <div className="space-y-6 text-gray-700">
            <p className="text-lg">
              <strong>Important Notice:</strong>
            </p>

            <ul className="list-disc pl-6 space-y-4">
              <li>
                Information generated by the App is for{" "}
                <strong>educational and informational purposes only</strong>.
              </li>
              <li>
                The App does not provide professional medical advice and should
                not be used to diagnose, treat, cure, or prevent any disease.
              </li>
              <li>
                Always seek the guidance of a{" "}
                <strong>qualified healthcare professional</strong> before making
                changes to your diet, exercise, or lifestyle.
              </li>
              <li>
                Reliance on information provided by this App is{" "}
                <strong>solely at your own risk</strong>.
              </li>
            </ul>

            <div className="mt-8 p-6 bg-red-50 border-l-4 border-red-400">
              <p className="text-gray-800 font-semibold">
                ⚕️ Medical Disclaimer
              </p>
              <p className="mt-2 text-gray-700">
                If you have any medical conditions, allergies, or are taking
                medications, consult with your doctor or a registered dietitian
                before following any diet or nutrition plan generated by this
                application.
              </p>
            </div>

            <div className="mt-6 p-6 bg-blue-50 border-l-4 border-blue-400">
              <p className="text-gray-800 font-semibold">
                🤖 AI-Generated Content
              </p>
              <p className="mt-2 text-gray-700">
                The nutrition plans and recommendations are generated by
                artificial intelligence and may not be suitable for everyone.
                Individual results may vary. The AI may make mistakes or provide
                information that is not appropriate for your specific health
                situation.
              </p>
            </div>
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <a href="/" className="text-blue-600 hover:text-blue-800 font-medium">
            ← Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}
