import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Logo } from '@/components/Logo';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

export default function DisclaimerPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-4 bg-background">
      <div className="w-full max-w-4xl space-y-8">
        <Card className="shadow-2xl bg-card/80 backdrop-blur-sm border-border">
          <CardHeader className="text-center">
             <div className="flex justify-center mb-4">
              <Link href="/" className="flex items-center gap-2">
                <Logo className="h-10 w-10 text-primary" />
                 <span className="text-xl font-bold font-headline text-foreground">
                    WellNourish AI
                </span>
              </Link>
            </div>
            <CardTitle className="font-headline text-3xl">Disclaimer</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-muted-foreground text-center">
            <p className="font-semibold text-foreground">
              For Informational Purposes Only
            </p>
            <p>
              The diet plans, workout routines, health tips, and all other information provided by the WellNourish AI application ("the Service") are generated by an artificial intelligence model. This information is intended for general informational and educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.
            </p>
            <p className="font-semibold text-foreground">
                Not Medical Advice
            </p>
            <p>
                The Service is not a licensed medical care provider. Always seek the advice of your physician or another qualified health provider with any questions you may have regarding a medical condition or before starting any new diet or fitness program. Never disregard professional medical advice or delay in seeking it because of something you have read or received from the Service.
            </p>
             <p className="font-semibold text-foreground">
                No Guarantees
            </p>
            <p>
                WellNourish AI makes no guarantees concerning the level of success you may experience, and you accept the risk that the results will differ for each individual. The use of our information, products, and services should be based on your own due diligence and you agree that the Company is not liable for any success or failure of your physique that is directly or indirectly related to the purchase and use of our information, products, and services.
            </p>
            <p className="font-semibold text-foreground">
                Assumption of Risk
            </p>
            <p>
                You expressly agree that your athletic activities, which may generate the User-Generated Content you post or seek to post on or via the App (e.g., running, cycling, hiking), carry certain inherent and significant risks of property damage, bodily injury or death and that you voluntarily assume all known and unknown risks associated with these activities even if caused in whole or part by the action, inaction or negligence of WellNourish AI or by the action, inaction or negligence of others.
            </p>
             <div className="pt-4">
                <Button asChild>
                    <Link href="/">Back to Home</Link>
                </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
