import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Logo } from "@/components/Logo";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer",
};

export default function DisclaimerPage() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background p-4 sm:p-6 md:p-8">
      <div className="absolute top-8 left-8">
        <Logo />
      </div>
      <div className="w-full max-w-4xl">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="text-3xl font-headline text-center">
              Disclaimer
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-muted-foreground">
            <p>
              The information provided by WellNourish AI, including but not
              limited to diet plans, workout routines, and health tips, is for
              informational and educational purposes only. It is not intended as
              a substitute for professional medical advice, diagnosis, or
              treatment.
            </p>
            <p>
              Always seek the advice of your physician or other qualified health
              provider with any questions you may have regarding a medical
              condition. Never disregard professional medical advice or delay in
              seeking it because of something you have read or received from
              this application.
            </p>
            <p>
              The use of any information provided by this app is solely at your
              own risk. WellNourish AI and its creators are not responsible or
              liable for any advice, course of treatment, diagnosis, or any
              other information, services, or products that you obtain through
              this application.
            </p>
            <p>
              By using WellNourish AI, you acknowledge that you are responsible
              for your own health decisions. The dietary and fitness plans
              generated by our AI are based on the data you provide and may not
              be suitable for everyone. Consult with a healthcare professional
              before starting any new diet or exercise program.
            </p>
            <div className="pt-6 text-center">
              <Button asChild>
                <Link href="/">
                  <ArrowLeft className="mr-2 h-4 w-4" />
                  Back to Home
                </Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
